<div class="content-header">
    <h3 class="icon-head head-adminhtml-import">Harvey Import / Export Data</h3>
</div>
<div class="entry-edit" id="export_filter_container">
    
        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
        <div id="export_filter_grid_container" class="fieldset">
            
            <div style="padding-bottom:20px">
                <label>Export file from Magento to Harvey</label>            
                <button class="scalable" type="button" onclick="exportFile();"><span><?php echo $this->__('Export') ?></span></button>
                <div id="notice_export"></div>
            </div>
            
            <div>
                <label>Import EXPORT.DAT file from Harvey to Magento</label>
                <button class="scalable" type="button" onclick="importFile();"><span><?php echo $this->__('Import') ?></span></button>
                <div id="notice_import"></div>
            </div>
        </div>
</div>
<script type="text/javascript">
function exportFile() {
    <?php $key = Mage::getSingleton('adminhtml/url')->getSecretKey("adminhtml_ship","export"); ?>
    var url = '<?php echo $this->getBaseUrl() ?>harvey/adminhtml_ship/export/key/<?php echo $key;?>';
    //alert(url);

    new Ajax.Request(url, {
      method: 'get',
      onSuccess: function(transport) { 
        var notice = $('notice_export');
        if (transport.responseText == 'Successfully exported data')
            notice.update(transport.responseText).setStyle({ background: '#dfd' });
        else
            notice.update(transport.responseText).setStyle({ background: '#fdd' });
      }
    });
}

function importFile() {
    <?php $key = Mage::getSingleton('adminhtml/url')->getSecretKey("adminhtml_ship","import"); ?>
    var url = '<?php echo $this->getBaseUrl() ?>harvey/adminhtml_ship/import/key/<?php echo $key;?>';
    //alert(url);

    new Ajax.Request(url, {
      method: 'get',
      onSuccess: function(transport) {
        var notice = $('notice_import');
        if (transport.responseText == 'Successfully imported data')
            notice.update(transport.responseText).setStyle({ background: '#dfd' });
        else
            notice.update(transport.responseText).setStyle({ background: '#fdd' });
        
      }
    });
}
</script>
