<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Sarp
 * @version    1.0
 * @deprecated
 * @copyright  Copyright (c) 2008-2009 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php echo $this->__("Dear %s", $this->getCustomer()->getName()); ?>,
<br/>
<?php echo $this->__("You have canceled") ?> <a
        href="<?php echo Mage::getUrl('sarp/customer/view', array('id' => $this->getSubscription()->getId()))?>"><?php echo $this->__("the subscription")?></a>
<br/>
<?php echo $this->__("To resume the subscription, please follow the") ?> <a
        href="<?php echo Mage::getUrl('sarp/customer/view', array('id' => $this->getSubscription()->getId()))?>"><?php echo $this->__("page")?></a>.
