<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Sarp
 * @version    1.0
 * @copyright  Copyright (c) 2009-2010 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php if ($this->getSubscription()->isActive()): ?>
<strong><?php echo $this->__('Next payment')?></strong>: <?php echo $this->formatDate($this->getNextPaymentDate(), Mage_Core_Model_Locale::FORMAT_TYPE_LONG) ?>
<?php endif; ?>
