<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Sarp
 * @version    1.0
 * @deprecated
 * @copyright  Copyright (c) 2008-2009 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php echo $this->__("Dear %s", $this->getCustomer()->getName()); ?>,
<br/>
<?php echo $this->__("We would like to inform that your subscription starts at %s", $this->formatDate($this->getSubscription()->getDateStart())) ?>

