<?php $url = Mage::getBaseUrl('media')."unleashed/"; ?>
<div id="formtoppattern">
    <img id="unleashed-logo" src="<?php echo $url."image003.png"; ?>" >
    <div id="formbot">
<?php
$this->exportProducts();
?>

    
    
        <div class="clear"></div>
        <div class="links_footer">
            <ul>
                <li><a href="https://go.unleashedsoftware.com/v2/Account/Register" target="_BLANK">Free 14 Day Unleashed Software Trial</a></li>
                <li>&nbsp;&nbsp;|&nbsp;&nbsp;</li>
                <li><a href="http://unleashedsoftware.com/magento/MagentoIntegration.pdf" target="_BLANK">Unleashed Integration Documentation</a></li>
                <li>&nbsp;&nbsp;|&nbsp;&nbsp;</li>
                <li><a href="http://support.unleashedsoftware.com" target="_BLANK">Unleashed Support Portal</a></li>
                <li>&nbsp;&nbsp;|&nbsp;&nbsp;</li>
                <li><a href="http://unleashedsoftware.com/blog/?page_id=218" target="_BLANK">Installation & Setup Assistance</a></li>
                <li>&nbsp;&nbsp;|&nbsp;&nbsp;</li>
                <li><a href="mailto:support@unleashedsoftware.com" target="_BLANK">Troubleshoot Assistance and Advice</a></li>
            </ul>
            
           
        </div>
    </div>
</div>