<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Sarp
 * @version    1.0
 * @deprecated
 * @copyright  Copyright (c) 2008-2009 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<a href="<?php echo $this->getUrl('adminhtml/customer/edit', array('id' => $this->getCustomer()->getId()));?>"><?php echo $this->getCustomer()->getName()?></a>
<?php echo $this->__("has subscribed to") ?>
<a href="<?php echo Mage::getUrl('sarp_admin/subscriptions/edit', array('id' => $this->getSubscription()->getId()))?>"><?php echo $this->__("subscription")?></a>

